ALTER TABLE `Doc` DROP FOREIGN KEY `Doc_fk0`;

ALTER TABLE `Doc` DROP FOREIGN KEY `Doc_fk1`;

ALTER TABLE `Shedule` DROP FOREIGN KEY `Shedule_fk0`;

ALTER TABLE `Shedule` DROP FOREIGN KEY `Shedule_fk1`;

ALTER TABLE `Shedule` DROP FOREIGN KEY `Shedule_fk2`;

ALTER TABLE `Diagnos` DROP FOREIGN KEY `Diagnos_fk0`;

ALTER TABLE `Diagnos` DROP FOREIGN KEY `Diagnos_fk1`;

ALTER TABLE `History` DROP FOREIGN KEY `History_fk0`;

ALTER TABLE `History` DROP FOREIGN KEY `History_fk1`;

